name: Upload CSV

on:
  push:
    branches:
      - calculator

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload CSV to server
        run: |
          mkdir -p uploads
          timestamp=$(date +%Y%m%d%H%M%S)
          echo "${{ secrets.CSV_CONTENT }}" > uploads/checklist_$timestamp.csv
